url: "https://lucasgeron.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Lucas Geron" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
  - jekyll-archives
  - jekyll-seo-tag

languages: ["pt-br", "en"]

exclude_from_localizations: ["javascript", "images", "css"]

email: lucasf.geron@gmail.com
description:  Bem-vindo ao meu site, onde você encontrará informações sobre meus projetos e habilidades em desenvolvimento web. Explore meus últimos projetos e entre em contato para saber mais.

highlighter: rouge


jekyll-archives:
  enabled: 
    - year
    - month
    - tags
    - categories
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'
  layout: archive
  # layouts:
  #   year: year-archive
  #   month: month-archive
  #   category: category-archive
  #   tag: tag-archive