url: "https://lucasgeron.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "lucasgeron at github" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-feed