url: "https://lucasgeron.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Lucas Geron" # the name of your site, e.g. ACME Corp.
description: Portfolio of Lucas Geron - Software Engineer. Explore my professional experience, skills and projects.

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

sass:
  sourcemap: never

postcss:
  cache: false

# Configuration for jekyll-multiple-languages-plugin
languages: ["en", "br"]
# To avoid redundancy, it is possible to exclude files and folders from being copied to the localization folders.
exclude_from_localizations: ["javascript", "images", "css"]


exclude:
  - .gitignore
  - bin
  - node_modules
  - package-lock.json
  - postcss.config.js
  - README.md
  # - assets/css/tailwind.scss

# files Jekyll should not delete from .site
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map