url: "https://lucasgeron.github.io" 
baseurl: "" 
title: "Lucas Geron"
tagline: "Software Engineer"
description: Explore my professional experience, skills and projects.
logo: "/assets/images/favicon.ico"
author: 
  name: "Lucas Geron"
  email: "lucasf.geron@gmail.com"
  github: "lucasgeron"
  linkedin: "lucasgeron"

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

sass:
  sourcemap: never

postcss:
  cache: false

# Configuration for jekyll-multiple-languages-plugin
languages: ["en", "br"]
# To avoid redundancy, it is possible to exclude files and folders from being copied to the localization folders.
exclude_from_localizations: ["javascript", "images", "css"]


exclude:
  - .gitignore
  - bin
  - node_modules
  - package-lock.json
  - postcss.config.js
  - README.md
  # - assets/css/tailwind.scss

# files Jekyll should not delete from .site
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map