#!/bin/bash


# Get current date, year, and month
DATE=$(date +"%Y-%m-%d")
YEAR=$(date +"%Y")
MONTH=$(date +"%m")

# Get title from user input
echo "Post Title:"
read TITLE

echo "Post Slug:"
read SLUG

echo "Language:"
read LANGUAGE

echo "Short Description:"
read SHORT_DESCRIPTION

echo "Cover URL:"
read COVER

echo "Labels:"
read LABEL

# Create year and month directories if they don't exist
mkdir -p _i18n/$LANGUAGE/_posts/$YEAR/$MONTH

# Create the file with YAML frontmatter
cat > _i18n/$LANGUAGE/_posts/$YEAR/$MONTH/$DATE-$SLUG.markdown << EOL
---

layout: post
title: "$TITLE"
date: $DATE
short_description: "$SHORT_DESCRIPTION"
cover: $COVER
labels: "$LABEL"

---

# $TITLE
$SHORT_DESCRIPTION

<div>
  <img src="$COVER" alt="" class=" w-100 img-fluid rounded-3 shadow mb-4">
</div>

This post was generated by ./post.sh

EOL

